# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbCartoControl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PbConsts_pb2 as PbConsts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbCartoControl.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x14PbCartoControl.proto\x12\x02pb\x1a\x0ePbConsts.proto\"\xad\x01\n\x0ePbRelocSummary\x12 \n\x18nodesInCurrentTrajectory\x18\x01 \x01(\r\x12#\n\x1bnodesInPreviousTrajectories\x18\x02 \x01(\r\x12)\n!currentTrajectoryIntraConstraints\x18\x03 \x01(\r\x12)\n!currentTrajectoryInterConstraints\x18\x04 \x01(\r\"\x84\x01\n\x0cPbCartoInput\x12 \n\x08\x63\x61rtoCmd\x18\x01 \x01(\x0e\x32\x0c.pb.CartoCmdH\x00\x12\x19\n\x0ftempFloorHashID\x18\x02 \x01(\tH\x01\x12\x12\n\nfloorHashs\x18\x03 \x03(\tB\r\n\x0bhasCartoCmdB\x14\n\x12hasTempFloorHashID\"\x9e\x02\n\rPbCartoOutput\x12&\n\x0cstateSignals\x18\x01 \x03(\x0e\x32\x10.pb.StateSignalT\x12#\n\twarnCodes\x18\x02 \x03(\x0e\x32\x10.pb.WarningCodeT\x12\"\n\nerrorCodes\x18\x03 \x03(\x0e\x32\x0e.pb.ErrorCodeT\x12\x1a\n\x10relocFloorHashID\x18\x04 \x01(\tH\x00\x12*\n\x0crelocSummary\x18\x05 \x01(\x0b\x32\x12.pb.PbRelocSummaryH\x01\x12\x17\n\rsaveMapFinish\x18\x06 \x01(\rH\x02\x42\x15\n\x13hasRelocFloorHashIDB\x11\n\x0fhasRelocSummaryB\x11\n\x0fisSaveMapFinishB\x02H\x03\x62\x06proto3')
  ,
  dependencies=[PbConsts__pb2.DESCRIPTOR,])




_PBRELOCSUMMARY = _descriptor.Descriptor(
  name='PbRelocSummary',
  full_name='pb.PbRelocSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodesInCurrentTrajectory', full_name='pb.PbRelocSummary.nodesInCurrentTrajectory', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodesInPreviousTrajectories', full_name='pb.PbRelocSummary.nodesInPreviousTrajectories', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentTrajectoryIntraConstraints', full_name='pb.PbRelocSummary.currentTrajectoryIntraConstraints', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentTrajectoryInterConstraints', full_name='pb.PbRelocSummary.currentTrajectoryInterConstraints', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=218,
)


_PBCARTOINPUT = _descriptor.Descriptor(
  name='PbCartoInput',
  full_name='pb.PbCartoInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cartoCmd', full_name='pb.PbCartoInput.cartoCmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tempFloorHashID', full_name='pb.PbCartoInput.tempFloorHashID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floorHashs', full_name='pb.PbCartoInput.floorHashs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasCartoCmd', full_name='pb.PbCartoInput.hasCartoCmd',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasTempFloorHashID', full_name='pb.PbCartoInput.hasTempFloorHashID',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=221,
  serialized_end=353,
)


_PBCARTOOUTPUT = _descriptor.Descriptor(
  name='PbCartoOutput',
  full_name='pb.PbCartoOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stateSignals', full_name='pb.PbCartoOutput.stateSignals', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warnCodes', full_name='pb.PbCartoOutput.warnCodes', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorCodes', full_name='pb.PbCartoOutput.errorCodes', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relocFloorHashID', full_name='pb.PbCartoOutput.relocFloorHashID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relocSummary', full_name='pb.PbCartoOutput.relocSummary', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='saveMapFinish', full_name='pb.PbCartoOutput.saveMapFinish', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasRelocFloorHashID', full_name='pb.PbCartoOutput.hasRelocFloorHashID',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasRelocSummary', full_name='pb.PbCartoOutput.hasRelocSummary',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='isSaveMapFinish', full_name='pb.PbCartoOutput.isSaveMapFinish',
      index=2, containing_type=None, fields=[]),
  ],
  serialized_start=356,
  serialized_end=642,
)

_PBCARTOINPUT.fields_by_name['cartoCmd'].enum_type = PbConsts__pb2._CARTOCMD
_PBCARTOINPUT.oneofs_by_name['hasCartoCmd'].fields.append(
  _PBCARTOINPUT.fields_by_name['cartoCmd'])
_PBCARTOINPUT.fields_by_name['cartoCmd'].containing_oneof = _PBCARTOINPUT.oneofs_by_name['hasCartoCmd']
_PBCARTOINPUT.oneofs_by_name['hasTempFloorHashID'].fields.append(
  _PBCARTOINPUT.fields_by_name['tempFloorHashID'])
_PBCARTOINPUT.fields_by_name['tempFloorHashID'].containing_oneof = _PBCARTOINPUT.oneofs_by_name['hasTempFloorHashID']
_PBCARTOOUTPUT.fields_by_name['stateSignals'].enum_type = PbConsts__pb2._STATESIGNALT
_PBCARTOOUTPUT.fields_by_name['warnCodes'].enum_type = PbConsts__pb2._WARNINGCODET
_PBCARTOOUTPUT.fields_by_name['errorCodes'].enum_type = PbConsts__pb2._ERRORCODET
_PBCARTOOUTPUT.fields_by_name['relocSummary'].message_type = _PBRELOCSUMMARY
_PBCARTOOUTPUT.oneofs_by_name['hasRelocFloorHashID'].fields.append(
  _PBCARTOOUTPUT.fields_by_name['relocFloorHashID'])
_PBCARTOOUTPUT.fields_by_name['relocFloorHashID'].containing_oneof = _PBCARTOOUTPUT.oneofs_by_name['hasRelocFloorHashID']
_PBCARTOOUTPUT.oneofs_by_name['hasRelocSummary'].fields.append(
  _PBCARTOOUTPUT.fields_by_name['relocSummary'])
_PBCARTOOUTPUT.fields_by_name['relocSummary'].containing_oneof = _PBCARTOOUTPUT.oneofs_by_name['hasRelocSummary']
_PBCARTOOUTPUT.oneofs_by_name['isSaveMapFinish'].fields.append(
  _PBCARTOOUTPUT.fields_by_name['saveMapFinish'])
_PBCARTOOUTPUT.fields_by_name['saveMapFinish'].containing_oneof = _PBCARTOOUTPUT.oneofs_by_name['isSaveMapFinish']
DESCRIPTOR.message_types_by_name['PbRelocSummary'] = _PBRELOCSUMMARY
DESCRIPTOR.message_types_by_name['PbCartoInput'] = _PBCARTOINPUT
DESCRIPTOR.message_types_by_name['PbCartoOutput'] = _PBCARTOOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbRelocSummary = _reflection.GeneratedProtocolMessageType('PbRelocSummary', (_message.Message,), dict(
  DESCRIPTOR = _PBRELOCSUMMARY,
  __module__ = 'PbCartoControl_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbRelocSummary)
  ))
_sym_db.RegisterMessage(PbRelocSummary)

PbCartoInput = _reflection.GeneratedProtocolMessageType('PbCartoInput', (_message.Message,), dict(
  DESCRIPTOR = _PBCARTOINPUT,
  __module__ = 'PbCartoControl_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbCartoInput)
  ))
_sym_db.RegisterMessage(PbCartoInput)

PbCartoOutput = _reflection.GeneratedProtocolMessageType('PbCartoOutput', (_message.Message,), dict(
  DESCRIPTOR = _PBCARTOOUTPUT,
  __module__ = 'PbCartoControl_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbCartoOutput)
  ))
_sym_db.RegisterMessage(PbCartoOutput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
