# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbConfigs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PbConsts_pb2 as PbConsts__pb2
from . import PbMessages_pb2 as PbMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbConfigs.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0fPbConfigs.proto\x12\x02pb\x1a\x0ePbConsts.proto\x1a\x10PbMessages.proto\"\xd9\x07\n\x08PbConfig\x12$\n\tcleanMode\x18\x01 \x01(\x0b\x32\x0f.pb.PbCleanModeH\x00\x12\x10\n\x06volume\x18\x02 \x01(\x05H\x01\x12\x14\n\ncleanSpeed\x18\x03 \x01(\x05H\x02\x12\x15\n\x0blanguagePkg\x18\x04 \x01(\tH\x03\x12&\n\x0cscheduleData\x18\x06 \x01(\x0b\x32\x0e.pb.PbScheduleH\x04\x12&\n\rAEDModeEnable\x18\x07 \x01(\x0e\x32\r.pb.PbToggleTH\x05\x12%\n\x0cRRModeEnable\x18\x08 \x01(\x0e\x32\r.pb.PbToggleTH\x06\x12$\n\x0b\x62oxLifeMode\x18\t \x01(\x0e\x32\r.pb.PbToggleTH\x07\x12\x12\n\x08timeZone\x18\n \x01(\x05H\x08\x12\x11\n\x07napTime\x18\x0b \x01(\x05H\t\x12)\n\x10roomByRoomEnable\x18\x0c \x01(\x0e\x32\r.pb.PbToggleTH\n\x12\x36\n\x1d\x63ontinueCrossHatchCleanEnable\x18\r \x01(\x0e\x32\r.pb.PbToggleTH\x0b\x12%\n\x0c\x66\x61nJetEnable\x18\x0e \x01(\x0e\x32\r.pb.PbToggleTH\x0c\x12\x31\n\x10\x63\x61rpetDetectMode\x18\x0f \x01(\x0e\x32\x15.pb.CarpetDetectModeTH\r\x12\x15\n\x0b\x66\x61nJetSpeed\x18\x10 \x01(\x05H\x0e\x12\x15\n\x0b\x61\x65\x64Interval\x18\x11 \x01(\x05H\x0f\x12+\n\x12\x64oNotDisturbEnable\x18\x12 \x01(\x0e\x32\r.pb.PbToggleTH\x10\x12-\n\x14\x63\x61rpetPressureEnable\x18\x13 \x01(\x0e\x32\r.pb.PbToggleTH\x11\x42\x0e\n\x0chasCleanModeB\x0e\n\x0chasVolumeCtrB\x12\n\x10hasCleanSpeedCtrB\x10\n\x0ehasLanguagePkgB\r\n\x0bhasScheduleB\x0e\n\x0chasAEDEnableB\r\n\x0bhasRREnableB\x0f\n\rhasSetBoxLifeB\r\n\x0bhasTimeZoneB\x0c\n\nhasNapTimeB\x15\n\x13hasRoomByRoomEnableB\"\n hasContinueCrossHatchCleanEnableB\x11\n\x0fhasFanJetEnableB\x15\n\x13hasCarpetDetectModeB\x10\n\x0ehasFanJetSpeedB\x10\n\x0ehasAEDIntervalB\x17\n\x15hasDoNotDisturbEnableB\x19\n\x17hasCarpetPressureEnableB\x02H\x03\x62\x06proto3')
  ,
  dependencies=[PbConsts__pb2.DESCRIPTOR,PbMessages__pb2.DESCRIPTOR,])




_PBCONFIG = _descriptor.Descriptor(
  name='PbConfig',
  full_name='pb.PbConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cleanMode', full_name='pb.PbConfig.cleanMode', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='pb.PbConfig.volume', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cleanSpeed', full_name='pb.PbConfig.cleanSpeed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='languagePkg', full_name='pb.PbConfig.languagePkg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheduleData', full_name='pb.PbConfig.scheduleData', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AEDModeEnable', full_name='pb.PbConfig.AEDModeEnable', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RRModeEnable', full_name='pb.PbConfig.RRModeEnable', index=6,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxLifeMode', full_name='pb.PbConfig.boxLifeMode', index=7,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeZone', full_name='pb.PbConfig.timeZone', index=8,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='napTime', full_name='pb.PbConfig.napTime', index=9,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roomByRoomEnable', full_name='pb.PbConfig.roomByRoomEnable', index=10,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='continueCrossHatchCleanEnable', full_name='pb.PbConfig.continueCrossHatchCleanEnable', index=11,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fanJetEnable', full_name='pb.PbConfig.fanJetEnable', index=12,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carpetDetectMode', full_name='pb.PbConfig.carpetDetectMode', index=13,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fanJetSpeed', full_name='pb.PbConfig.fanJetSpeed', index=14,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aedInterval', full_name='pb.PbConfig.aedInterval', index=15,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doNotDisturbEnable', full_name='pb.PbConfig.doNotDisturbEnable', index=16,
      number=18, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carpetPressureEnable', full_name='pb.PbConfig.carpetPressureEnable', index=17,
      number=19, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasCleanMode', full_name='pb.PbConfig.hasCleanMode',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasVolumeCtr', full_name='pb.PbConfig.hasVolumeCtr',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasCleanSpeedCtr', full_name='pb.PbConfig.hasCleanSpeedCtr',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasLanguagePkg', full_name='pb.PbConfig.hasLanguagePkg',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasSchedule', full_name='pb.PbConfig.hasSchedule',
      index=4, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasAEDEnable', full_name='pb.PbConfig.hasAEDEnable',
      index=5, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasRREnable', full_name='pb.PbConfig.hasRREnable',
      index=6, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasSetBoxLife', full_name='pb.PbConfig.hasSetBoxLife',
      index=7, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasTimeZone', full_name='pb.PbConfig.hasTimeZone',
      index=8, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasNapTime', full_name='pb.PbConfig.hasNapTime',
      index=9, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasRoomByRoomEnable', full_name='pb.PbConfig.hasRoomByRoomEnable',
      index=10, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasContinueCrossHatchCleanEnable', full_name='pb.PbConfig.hasContinueCrossHatchCleanEnable',
      index=11, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasFanJetEnable', full_name='pb.PbConfig.hasFanJetEnable',
      index=12, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasCarpetDetectMode', full_name='pb.PbConfig.hasCarpetDetectMode',
      index=13, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasFanJetSpeed', full_name='pb.PbConfig.hasFanJetSpeed',
      index=14, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasAEDInterval', full_name='pb.PbConfig.hasAEDInterval',
      index=15, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasDoNotDisturbEnable', full_name='pb.PbConfig.hasDoNotDisturbEnable',
      index=16, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasCarpetPressureEnable', full_name='pb.PbConfig.hasCarpetPressureEnable',
      index=17, containing_type=None, fields=[]),
  ],
  serialized_start=58,
  serialized_end=1043,
)

_PBCONFIG.fields_by_name['cleanMode'].message_type = PbMessages__pb2._PBCLEANMODE
_PBCONFIG.fields_by_name['scheduleData'].message_type = PbMessages__pb2._PBSCHEDULE
_PBCONFIG.fields_by_name['AEDModeEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['RRModeEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['boxLifeMode'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['roomByRoomEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['continueCrossHatchCleanEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['fanJetEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['carpetDetectMode'].enum_type = PbConsts__pb2._CARPETDETECTMODET
_PBCONFIG.fields_by_name['doNotDisturbEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.fields_by_name['carpetPressureEnable'].enum_type = PbConsts__pb2._PBTOGGLET
_PBCONFIG.oneofs_by_name['hasCleanMode'].fields.append(
  _PBCONFIG.fields_by_name['cleanMode'])
_PBCONFIG.fields_by_name['cleanMode'].containing_oneof = _PBCONFIG.oneofs_by_name['hasCleanMode']
_PBCONFIG.oneofs_by_name['hasVolumeCtr'].fields.append(
  _PBCONFIG.fields_by_name['volume'])
_PBCONFIG.fields_by_name['volume'].containing_oneof = _PBCONFIG.oneofs_by_name['hasVolumeCtr']
_PBCONFIG.oneofs_by_name['hasCleanSpeedCtr'].fields.append(
  _PBCONFIG.fields_by_name['cleanSpeed'])
_PBCONFIG.fields_by_name['cleanSpeed'].containing_oneof = _PBCONFIG.oneofs_by_name['hasCleanSpeedCtr']
_PBCONFIG.oneofs_by_name['hasLanguagePkg'].fields.append(
  _PBCONFIG.fields_by_name['languagePkg'])
_PBCONFIG.fields_by_name['languagePkg'].containing_oneof = _PBCONFIG.oneofs_by_name['hasLanguagePkg']
_PBCONFIG.oneofs_by_name['hasSchedule'].fields.append(
  _PBCONFIG.fields_by_name['scheduleData'])
_PBCONFIG.fields_by_name['scheduleData'].containing_oneof = _PBCONFIG.oneofs_by_name['hasSchedule']
_PBCONFIG.oneofs_by_name['hasAEDEnable'].fields.append(
  _PBCONFIG.fields_by_name['AEDModeEnable'])
_PBCONFIG.fields_by_name['AEDModeEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasAEDEnable']
_PBCONFIG.oneofs_by_name['hasRREnable'].fields.append(
  _PBCONFIG.fields_by_name['RRModeEnable'])
_PBCONFIG.fields_by_name['RRModeEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasRREnable']
_PBCONFIG.oneofs_by_name['hasSetBoxLife'].fields.append(
  _PBCONFIG.fields_by_name['boxLifeMode'])
_PBCONFIG.fields_by_name['boxLifeMode'].containing_oneof = _PBCONFIG.oneofs_by_name['hasSetBoxLife']
_PBCONFIG.oneofs_by_name['hasTimeZone'].fields.append(
  _PBCONFIG.fields_by_name['timeZone'])
_PBCONFIG.fields_by_name['timeZone'].containing_oneof = _PBCONFIG.oneofs_by_name['hasTimeZone']
_PBCONFIG.oneofs_by_name['hasNapTime'].fields.append(
  _PBCONFIG.fields_by_name['napTime'])
_PBCONFIG.fields_by_name['napTime'].containing_oneof = _PBCONFIG.oneofs_by_name['hasNapTime']
_PBCONFIG.oneofs_by_name['hasRoomByRoomEnable'].fields.append(
  _PBCONFIG.fields_by_name['roomByRoomEnable'])
_PBCONFIG.fields_by_name['roomByRoomEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasRoomByRoomEnable']
_PBCONFIG.oneofs_by_name['hasContinueCrossHatchCleanEnable'].fields.append(
  _PBCONFIG.fields_by_name['continueCrossHatchCleanEnable'])
_PBCONFIG.fields_by_name['continueCrossHatchCleanEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasContinueCrossHatchCleanEnable']
_PBCONFIG.oneofs_by_name['hasFanJetEnable'].fields.append(
  _PBCONFIG.fields_by_name['fanJetEnable'])
_PBCONFIG.fields_by_name['fanJetEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasFanJetEnable']
_PBCONFIG.oneofs_by_name['hasCarpetDetectMode'].fields.append(
  _PBCONFIG.fields_by_name['carpetDetectMode'])
_PBCONFIG.fields_by_name['carpetDetectMode'].containing_oneof = _PBCONFIG.oneofs_by_name['hasCarpetDetectMode']
_PBCONFIG.oneofs_by_name['hasFanJetSpeed'].fields.append(
  _PBCONFIG.fields_by_name['fanJetSpeed'])
_PBCONFIG.fields_by_name['fanJetSpeed'].containing_oneof = _PBCONFIG.oneofs_by_name['hasFanJetSpeed']
_PBCONFIG.oneofs_by_name['hasAEDInterval'].fields.append(
  _PBCONFIG.fields_by_name['aedInterval'])
_PBCONFIG.fields_by_name['aedInterval'].containing_oneof = _PBCONFIG.oneofs_by_name['hasAEDInterval']
_PBCONFIG.oneofs_by_name['hasDoNotDisturbEnable'].fields.append(
  _PBCONFIG.fields_by_name['doNotDisturbEnable'])
_PBCONFIG.fields_by_name['doNotDisturbEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasDoNotDisturbEnable']
_PBCONFIG.oneofs_by_name['hasCarpetPressureEnable'].fields.append(
  _PBCONFIG.fields_by_name['carpetPressureEnable'])
_PBCONFIG.fields_by_name['carpetPressureEnable'].containing_oneof = _PBCONFIG.oneofs_by_name['hasCarpetPressureEnable']
DESCRIPTOR.message_types_by_name['PbConfig'] = _PBCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbConfig = _reflection.GeneratedProtocolMessageType('PbConfig', (_message.Message,), dict(
  DESCRIPTOR = _PBCONFIG,
  __module__ = 'PbConfigs_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbConfig)
  ))
_sym_db.RegisterMessage(PbConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
