# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbDebug.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PbConsts_pb2 as PbConsts__pb2
from . import PbLidar_pb2 as PbLidar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbDebug.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\rPbDebug.proto\x12\x02pb\x1a\x0ePbConsts.proto\x1a\rPbLidar.proto\"\xe4\x03\n\x0cPbDbgSetting\x12$\n\ruploadLogFile\x18\x01 \x01(\x0e\x32\r.pb.PbToggleT\x12$\n\ruploadMapFile\x18\x02 \x01(\x0e\x32\r.pb.PbToggleT\x12\x0f\n\x07vtParam\x18\x03 \x01(\t\x12\x12\n\x08logLevel\x18\x04 \x01(\x05H\x00\x12$\n\x0b\x65nLogUpload\x18\x05 \x01(\x0e\x32\r.pb.PbToggleTH\x01\x12\x18\n\x0e\x62\x61tteryControl\x18\x07 \x01(\x05H\x02\x12\x15\n\rnetcatAddress\x18\x08 \x01(\t\x12\x12\n\nnetcatPort\x18\t \x01(\x05\x12\x1b\n\x11mapUploadInterval\x18\n \x01(\x05H\x03\x12!\n\nenableScan\x18\x0b \x01(\x0e\x32\r.pb.PbToggleT\x12\x10\n\x08\x62\x64pInput\x18\x0c \x01(\t\x12\x13\n\tsprayTime\x18\r \x01(\x05H\x04\x12%\n\x0cmopAgitation\x18\x0e \x01(\x0e\x32\r.pb.PbToggleTH\x05\x42\r\n\x0bhasLogLevelB\x0e\n\x0chasLogUploadB\x13\n\x11hasBatteryControlB\x13\n\x11hasUploadIntervalB\x0e\n\x0chasSprayTimeB\x11\n\x0fhasMopAgitation\"\x93\x02\n\tPbDbgInfo\x12$\n\x0b\x65nLogUpload\x18\x01 \x01(\x0e\x32\r.pb.PbToggleTH\x00\x12\x0c\n\x04logs\x18\x02 \x03(\t\x12$\n\ruploadLogFile\x18\x03 \x01(\x0e\x32\r.pb.PbToggleT\x12$\n\ruploadMapFile\x18\x04 \x01(\x0e\x32\r.pb.PbToggleT\x12\x15\n\ruploadPercent\x18\x05 \x01(\x05\x12\x0f\n\x07vtParam\x18\x06 \x01(\t\x12\x14\n\x0cloopVariance\x18\t \x01(\x02\x12\x11\n\tbdpOutput\x18\n \x01(\t\x12\x1a\n\x04scan\x18\x0b \x01(\x0b\x32\n.pb.PbScanH\x01\x42\x0e\n\x0chasLogUploadB\t\n\x07hasScanB\x02H\x03\x62\x06proto3')
  ,
  dependencies=[PbConsts__pb2.DESCRIPTOR,PbLidar__pb2.DESCRIPTOR,])




_PBDBGSETTING = _descriptor.Descriptor(
  name='PbDbgSetting',
  full_name='pb.PbDbgSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uploadLogFile', full_name='pb.PbDbgSetting.uploadLogFile', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploadMapFile', full_name='pb.PbDbgSetting.uploadMapFile', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vtParam', full_name='pb.PbDbgSetting.vtParam', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logLevel', full_name='pb.PbDbgSetting.logLevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enLogUpload', full_name='pb.PbDbgSetting.enLogUpload', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batteryControl', full_name='pb.PbDbgSetting.batteryControl', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='netcatAddress', full_name='pb.PbDbgSetting.netcatAddress', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='netcatPort', full_name='pb.PbDbgSetting.netcatPort', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapUploadInterval', full_name='pb.PbDbgSetting.mapUploadInterval', index=8,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enableScan', full_name='pb.PbDbgSetting.enableScan', index=9,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bdpInput', full_name='pb.PbDbgSetting.bdpInput', index=10,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sprayTime', full_name='pb.PbDbgSetting.sprayTime', index=11,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mopAgitation', full_name='pb.PbDbgSetting.mopAgitation', index=12,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasLogLevel', full_name='pb.PbDbgSetting.hasLogLevel',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasLogUpload', full_name='pb.PbDbgSetting.hasLogUpload',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasBatteryControl', full_name='pb.PbDbgSetting.hasBatteryControl',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasUploadInterval', full_name='pb.PbDbgSetting.hasUploadInterval',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasSprayTime', full_name='pb.PbDbgSetting.hasSprayTime',
      index=4, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasMopAgitation', full_name='pb.PbDbgSetting.hasMopAgitation',
      index=5, containing_type=None, fields=[]),
  ],
  serialized_start=53,
  serialized_end=537,
)


_PBDBGINFO = _descriptor.Descriptor(
  name='PbDbgInfo',
  full_name='pb.PbDbgInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enLogUpload', full_name='pb.PbDbgInfo.enLogUpload', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logs', full_name='pb.PbDbgInfo.logs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploadLogFile', full_name='pb.PbDbgInfo.uploadLogFile', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploadMapFile', full_name='pb.PbDbgInfo.uploadMapFile', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploadPercent', full_name='pb.PbDbgInfo.uploadPercent', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vtParam', full_name='pb.PbDbgInfo.vtParam', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loopVariance', full_name='pb.PbDbgInfo.loopVariance', index=6,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bdpOutput', full_name='pb.PbDbgInfo.bdpOutput', index=7,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scan', full_name='pb.PbDbgInfo.scan', index=8,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasLogUpload', full_name='pb.PbDbgInfo.hasLogUpload',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasScan', full_name='pb.PbDbgInfo.hasScan',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=540,
  serialized_end=815,
)

_PBDBGSETTING.fields_by_name['uploadLogFile'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGSETTING.fields_by_name['uploadMapFile'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGSETTING.fields_by_name['enLogUpload'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGSETTING.fields_by_name['enableScan'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGSETTING.fields_by_name['mopAgitation'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGSETTING.oneofs_by_name['hasLogLevel'].fields.append(
  _PBDBGSETTING.fields_by_name['logLevel'])
_PBDBGSETTING.fields_by_name['logLevel'].containing_oneof = _PBDBGSETTING.oneofs_by_name['hasLogLevel']
_PBDBGSETTING.oneofs_by_name['hasLogUpload'].fields.append(
  _PBDBGSETTING.fields_by_name['enLogUpload'])
_PBDBGSETTING.fields_by_name['enLogUpload'].containing_oneof = _PBDBGSETTING.oneofs_by_name['hasLogUpload']
_PBDBGSETTING.oneofs_by_name['hasBatteryControl'].fields.append(
  _PBDBGSETTING.fields_by_name['batteryControl'])
_PBDBGSETTING.fields_by_name['batteryControl'].containing_oneof = _PBDBGSETTING.oneofs_by_name['hasBatteryControl']
_PBDBGSETTING.oneofs_by_name['hasUploadInterval'].fields.append(
  _PBDBGSETTING.fields_by_name['mapUploadInterval'])
_PBDBGSETTING.fields_by_name['mapUploadInterval'].containing_oneof = _PBDBGSETTING.oneofs_by_name['hasUploadInterval']
_PBDBGSETTING.oneofs_by_name['hasSprayTime'].fields.append(
  _PBDBGSETTING.fields_by_name['sprayTime'])
_PBDBGSETTING.fields_by_name['sprayTime'].containing_oneof = _PBDBGSETTING.oneofs_by_name['hasSprayTime']
_PBDBGSETTING.oneofs_by_name['hasMopAgitation'].fields.append(
  _PBDBGSETTING.fields_by_name['mopAgitation'])
_PBDBGSETTING.fields_by_name['mopAgitation'].containing_oneof = _PBDBGSETTING.oneofs_by_name['hasMopAgitation']
_PBDBGINFO.fields_by_name['enLogUpload'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGINFO.fields_by_name['uploadLogFile'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGINFO.fields_by_name['uploadMapFile'].enum_type = PbConsts__pb2._PBTOGGLET
_PBDBGINFO.fields_by_name['scan'].message_type = PbLidar__pb2._PBSCAN
_PBDBGINFO.oneofs_by_name['hasLogUpload'].fields.append(
  _PBDBGINFO.fields_by_name['enLogUpload'])
_PBDBGINFO.fields_by_name['enLogUpload'].containing_oneof = _PBDBGINFO.oneofs_by_name['hasLogUpload']
_PBDBGINFO.oneofs_by_name['hasScan'].fields.append(
  _PBDBGINFO.fields_by_name['scan'])
_PBDBGINFO.fields_by_name['scan'].containing_oneof = _PBDBGINFO.oneofs_by_name['hasScan']
DESCRIPTOR.message_types_by_name['PbDbgSetting'] = _PBDBGSETTING
DESCRIPTOR.message_types_by_name['PbDbgInfo'] = _PBDBGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbDbgSetting = _reflection.GeneratedProtocolMessageType('PbDbgSetting', (_message.Message,), dict(
  DESCRIPTOR = _PBDBGSETTING,
  __module__ = 'PbDebug_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbDbgSetting)
  ))
_sym_db.RegisterMessage(PbDbgSetting)

PbDbgInfo = _reflection.GeneratedProtocolMessageType('PbDbgInfo', (_message.Message,), dict(
  DESCRIPTOR = _PBDBGINFO,
  __module__ = 'PbDebug_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbDbgInfo)
  ))
_sym_db.RegisterMessage(PbDbgInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
