# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbLidar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PbMessages_pb2 as PbMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbLidar.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\rPbLidar.proto\x12\x02pb\x1a\x10PbMessages.proto\"0\n\x0cPbRangePoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\n\n\x02st\x18\x03 \x01(\x02\"x\n\x06PbScan\x12\x12\n\nframe_name\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x05\x12!\n\nframe_pose\x18\x03 \x01(\x0b\x32\r.pb.PbPose2Df\x12%\n\x0brangePoints\x18\x04 \x03(\x0b\x32\x10.pb.PbRangePointB\x02H\x03\x62\x06proto3')
  ,
  dependencies=[PbMessages__pb2.DESCRIPTOR,])




_PBRANGEPOINT = _descriptor.Descriptor(
  name='PbRangePoint',
  full_name='pb.PbRangePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='pb.PbRangePoint.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='pb.PbRangePoint.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='st', full_name='pb.PbRangePoint.st', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=87,
)


_PBSCAN = _descriptor.Descriptor(
  name='PbScan',
  full_name='pb.PbScan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_name', full_name='pb.PbScan.frame_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='pb.PbScan.frame_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_pose', full_name='pb.PbScan.frame_pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rangePoints', full_name='pb.PbScan.rangePoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=209,
)

_PBSCAN.fields_by_name['frame_pose'].message_type = PbMessages__pb2._PBPOSE2DF
_PBSCAN.fields_by_name['rangePoints'].message_type = _PBRANGEPOINT
DESCRIPTOR.message_types_by_name['PbRangePoint'] = _PBRANGEPOINT
DESCRIPTOR.message_types_by_name['PbScan'] = _PBSCAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbRangePoint = _reflection.GeneratedProtocolMessageType('PbRangePoint', (_message.Message,), dict(
  DESCRIPTOR = _PBRANGEPOINT,
  __module__ = 'PbLidar_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbRangePoint)
  ))
_sym_db.RegisterMessage(PbRangePoint)

PbScan = _reflection.GeneratedProtocolMessageType('PbScan', (_message.Message,), dict(
  DESCRIPTOR = _PBSCAN,
  __module__ = 'PbLidar_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbScan)
  ))
_sym_db.RegisterMessage(PbScan)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
