# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbModules.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbModules.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0fPbModules.proto\x12\x02pb\"\x1d\n\x0fPbModulesStatus\x12\n\n\x02id\x18\x01 \x01(\x05\"\x98\x01\n\x10PbModulesRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x11modulesInitSignal\x18( \x01(\x05H\x00\x12\x1c\n\x12modulesCheckSignal\x18) \x01(\x05H\x01\x42\x16\n\x14hasModulesInitSignalB\x17\n\x15hasModulesCheckSignalB\x02H\x03\x62\x06proto3')
)




_PBMODULESSTATUS = _descriptor.Descriptor(
  name='PbModulesStatus',
  full_name='pb.PbModulesStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.PbModulesStatus.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)


_PBMODULESREQUEST = _descriptor.Descriptor(
  name='PbModulesRequest',
  full_name='pb.PbModulesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.PbModulesRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pb.PbModulesRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modulesInitSignal', full_name='pb.PbModulesRequest.modulesInitSignal', index=2,
      number=40, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modulesCheckSignal', full_name='pb.PbModulesRequest.modulesCheckSignal', index=3,
      number=41, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasModulesInitSignal', full_name='pb.PbModulesRequest.hasModulesInitSignal',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasModulesCheckSignal', full_name='pb.PbModulesRequest.hasModulesCheckSignal',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=55,
  serialized_end=207,
)

_PBMODULESREQUEST.oneofs_by_name['hasModulesInitSignal'].fields.append(
  _PBMODULESREQUEST.fields_by_name['modulesInitSignal'])
_PBMODULESREQUEST.fields_by_name['modulesInitSignal'].containing_oneof = _PBMODULESREQUEST.oneofs_by_name['hasModulesInitSignal']
_PBMODULESREQUEST.oneofs_by_name['hasModulesCheckSignal'].fields.append(
  _PBMODULESREQUEST.fields_by_name['modulesCheckSignal'])
_PBMODULESREQUEST.fields_by_name['modulesCheckSignal'].containing_oneof = _PBMODULESREQUEST.oneofs_by_name['hasModulesCheckSignal']
DESCRIPTOR.message_types_by_name['PbModulesStatus'] = _PBMODULESSTATUS
DESCRIPTOR.message_types_by_name['PbModulesRequest'] = _PBMODULESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbModulesStatus = _reflection.GeneratedProtocolMessageType('PbModulesStatus', (_message.Message,), dict(
  DESCRIPTOR = _PBMODULESSTATUS,
  __module__ = 'PbModules_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbModulesStatus)
  ))
_sym_db.RegisterMessage(PbModulesStatus)

PbModulesRequest = _reflection.GeneratedProtocolMessageType('PbModulesRequest', (_message.Message,), dict(
  DESCRIPTOR = _PBMODULESREQUEST,
  __module__ = 'PbModules_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbModulesRequest)
  ))
_sym_db.RegisterMessage(PbModulesRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
