# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbNetwork.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbNetwork.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0fPbNetwork.proto\x12\x02pb\"\x80\x01\n\x0bPbNetConfig\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x12\n\ndeviceName\x18\x04 \x01(\t\x12\x12\n\nproductKey\x18\x05 \x01(\t\x12\x0f\n\x07\x62\x64pssid\x18\x06 \x01(\t\x12\x0f\n\x07\x64snInfo\x18\x07 \x01(\t\"\xbb\x03\n\x0fPbDeviceProfile\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nversionL01\x18\x02 \x01(\t\x12\x11\n\tversionFW\x18\x03 \x01(\t\x12\x12\n\nversionMCU\x18\x04 \x01(\t\x12\x12\n\ndeviceName\x18\x05 \x01(\t\x12\x10\n\x08\x64\x65viceSN\x18\x06 \x01(\t\x12\x11\n\tipAddress\x18\x07 \x01(\t\x12\x12\n\nmacAddress\x18\x08 \x01(\t\x12\x15\n\rversionIOTLib\x18\t \x01(\t\x12\x14\n\x0cversionHWMCU\x18\n \x01(\t\x12\x14\n\x0cversionHWL01\x18\x0b \x01(\t\x12\x15\n\rversionHWWIFI\x18\x0c \x01(\t\x12\x14\n\x0cversionMCUBL\x18\r \x01(\t\x12\x12\n\nversionBDP\x18\x0e \x01(\t\x12\x14\n\x0cversionBDPDP\x18\x0f \x01(\t\x12\x14\n\x0cversionBDPDH\x18\x10 \x01(\t\x12\x12\n\nmoduleName\x18\x11 \x01(\t\x12\x0e\n\x06qrcode\x18\x12 \x01(\t\x12\x1a\n\x12hardwareDescriptor\x18\x13 \x01(\t\x12\x0b\n\x03SKU\x18\x14 \x01(\t\x12\x12\n\nRobotModel\x18\x15 \x01(\x05\"\xe4\x01\n\tPbOTAInfo\x12\x15\n\rtargetVersion\x18\x01 \x01(\t\x12\x12\n\x08progress\x18\x02 \x01(\x05H\x00\x12\x13\n\tchangeLog\x18\x03 \x01(\tH\x01\x12\r\n\x03MD5\x18\x04 \x01(\tH\x02\x12\x0e\n\x04size\x18\x05 \x01(\x05H\x03\x12\x11\n\tdirectory\x18\x06 \x01(\t\x12\x0c\n\x04urls\x18\x08 \x03(\t\x12\x13\n\totaSignal\x18\t \x01(\x05H\x04\x42\r\n\x0bhasProgressB\x0e\n\x0chasChangeLogB\x08\n\x06hasMD5B\t\n\x07hasSizeB\x0e\n\x0chasOtaSignalB\x02H\x03\x62\x06proto3')
)




_PBNETCONFIG = _descriptor.Descriptor(
  name='PbNetConfig',
  full_name='pb.PbNetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='pb.PbNetConfig.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwd', full_name='pb.PbNetConfig.pwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.PbNetConfig.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='pb.PbNetConfig.deviceName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productKey', full_name='pb.PbNetConfig.productKey', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bdpssid', full_name='pb.PbNetConfig.bdpssid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dsnInfo', full_name='pb.PbNetConfig.dsnInfo', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=152,
)


_PBDEVICEPROFILE = _descriptor.Descriptor(
  name='PbDeviceProfile',
  full_name='pb.PbDeviceProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='pb.PbDeviceProfile.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionL01', full_name='pb.PbDeviceProfile.versionL01', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionFW', full_name='pb.PbDeviceProfile.versionFW', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionMCU', full_name='pb.PbDeviceProfile.versionMCU', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='pb.PbDeviceProfile.deviceName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceSN', full_name='pb.PbDeviceProfile.deviceSN', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipAddress', full_name='pb.PbDeviceProfile.ipAddress', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='macAddress', full_name='pb.PbDeviceProfile.macAddress', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionIOTLib', full_name='pb.PbDeviceProfile.versionIOTLib', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionHWMCU', full_name='pb.PbDeviceProfile.versionHWMCU', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionHWL01', full_name='pb.PbDeviceProfile.versionHWL01', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionHWWIFI', full_name='pb.PbDeviceProfile.versionHWWIFI', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionMCUBL', full_name='pb.PbDeviceProfile.versionMCUBL', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionBDP', full_name='pb.PbDeviceProfile.versionBDP', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionBDPDP', full_name='pb.PbDeviceProfile.versionBDPDP', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionBDPDH', full_name='pb.PbDeviceProfile.versionBDPDH', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moduleName', full_name='pb.PbDeviceProfile.moduleName', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qrcode', full_name='pb.PbDeviceProfile.qrcode', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardwareDescriptor', full_name='pb.PbDeviceProfile.hardwareDescriptor', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SKU', full_name='pb.PbDeviceProfile.SKU', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RobotModel', full_name='pb.PbDeviceProfile.RobotModel', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=598,
)


_PBOTAINFO = _descriptor.Descriptor(
  name='PbOTAInfo',
  full_name='pb.PbOTAInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetVersion', full_name='pb.PbOTAInfo.targetVersion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='pb.PbOTAInfo.progress', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changeLog', full_name='pb.PbOTAInfo.changeLog', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MD5', full_name='pb.PbOTAInfo.MD5', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='pb.PbOTAInfo.size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='directory', full_name='pb.PbOTAInfo.directory', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urls', full_name='pb.PbOTAInfo.urls', index=6,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otaSignal', full_name='pb.PbOTAInfo.otaSignal', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasProgress', full_name='pb.PbOTAInfo.hasProgress',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasChangeLog', full_name='pb.PbOTAInfo.hasChangeLog',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasMD5', full_name='pb.PbOTAInfo.hasMD5',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasSize', full_name='pb.PbOTAInfo.hasSize',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasOtaSignal', full_name='pb.PbOTAInfo.hasOtaSignal',
      index=4, containing_type=None, fields=[]),
  ],
  serialized_start=601,
  serialized_end=829,
)

_PBOTAINFO.oneofs_by_name['hasProgress'].fields.append(
  _PBOTAINFO.fields_by_name['progress'])
_PBOTAINFO.fields_by_name['progress'].containing_oneof = _PBOTAINFO.oneofs_by_name['hasProgress']
_PBOTAINFO.oneofs_by_name['hasChangeLog'].fields.append(
  _PBOTAINFO.fields_by_name['changeLog'])
_PBOTAINFO.fields_by_name['changeLog'].containing_oneof = _PBOTAINFO.oneofs_by_name['hasChangeLog']
_PBOTAINFO.oneofs_by_name['hasMD5'].fields.append(
  _PBOTAINFO.fields_by_name['MD5'])
_PBOTAINFO.fields_by_name['MD5'].containing_oneof = _PBOTAINFO.oneofs_by_name['hasMD5']
_PBOTAINFO.oneofs_by_name['hasSize'].fields.append(
  _PBOTAINFO.fields_by_name['size'])
_PBOTAINFO.fields_by_name['size'].containing_oneof = _PBOTAINFO.oneofs_by_name['hasSize']
_PBOTAINFO.oneofs_by_name['hasOtaSignal'].fields.append(
  _PBOTAINFO.fields_by_name['otaSignal'])
_PBOTAINFO.fields_by_name['otaSignal'].containing_oneof = _PBOTAINFO.oneofs_by_name['hasOtaSignal']
DESCRIPTOR.message_types_by_name['PbNetConfig'] = _PBNETCONFIG
DESCRIPTOR.message_types_by_name['PbDeviceProfile'] = _PBDEVICEPROFILE
DESCRIPTOR.message_types_by_name['PbOTAInfo'] = _PBOTAINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbNetConfig = _reflection.GeneratedProtocolMessageType('PbNetConfig', (_message.Message,), dict(
  DESCRIPTOR = _PBNETCONFIG,
  __module__ = 'PbNetwork_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbNetConfig)
  ))
_sym_db.RegisterMessage(PbNetConfig)

PbDeviceProfile = _reflection.GeneratedProtocolMessageType('PbDeviceProfile', (_message.Message,), dict(
  DESCRIPTOR = _PBDEVICEPROFILE,
  __module__ = 'PbNetwork_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbDeviceProfile)
  ))
_sym_db.RegisterMessage(PbDeviceProfile)

PbOTAInfo = _reflection.GeneratedProtocolMessageType('PbOTAInfo', (_message.Message,), dict(
  DESCRIPTOR = _PBOTAINFO,
  __module__ = 'PbNetwork_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbOTAInfo)
  ))
_sym_db.RegisterMessage(PbOTAInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
