# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbQInternal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PbCartoControl_pb2 as PbCartoControl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbQInternal.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x11PbQInternal.proto\x12\x02pb\x1a\x14PbCartoControl.proto\"L\n\x11PbQInternalOutput\x12&\n\ncartoInput\x18\x01 \x01(\x0b\x32\x10.pb.PbCartoInputH\x00\x42\x0f\n\rhasCartoInput\"N\n\x10PbQInternalInput\x12(\n\x0b\x63\x61rtoOutput\x18\x01 \x01(\x0b\x32\x11.pb.PbCartoOutputH\x00\x42\x10\n\x0ehasCartoOutputB\x02H\x03\x62\x06proto3')
  ,
  dependencies=[PbCartoControl__pb2.DESCRIPTOR,])




_PBQINTERNALOUTPUT = _descriptor.Descriptor(
  name='PbQInternalOutput',
  full_name='pb.PbQInternalOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cartoInput', full_name='pb.PbQInternalOutput.cartoInput', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasCartoInput', full_name='pb.PbQInternalOutput.hasCartoInput',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=47,
  serialized_end=123,
)


_PBQINTERNALINPUT = _descriptor.Descriptor(
  name='PbQInternalInput',
  full_name='pb.PbQInternalInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cartoOutput', full_name='pb.PbQInternalInput.cartoOutput', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasCartoOutput', full_name='pb.PbQInternalInput.hasCartoOutput',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=125,
  serialized_end=203,
)

_PBQINTERNALOUTPUT.fields_by_name['cartoInput'].message_type = PbCartoControl__pb2._PBCARTOINPUT
_PBQINTERNALOUTPUT.oneofs_by_name['hasCartoInput'].fields.append(
  _PBQINTERNALOUTPUT.fields_by_name['cartoInput'])
_PBQINTERNALOUTPUT.fields_by_name['cartoInput'].containing_oneof = _PBQINTERNALOUTPUT.oneofs_by_name['hasCartoInput']
_PBQINTERNALINPUT.fields_by_name['cartoOutput'].message_type = PbCartoControl__pb2._PBCARTOOUTPUT
_PBQINTERNALINPUT.oneofs_by_name['hasCartoOutput'].fields.append(
  _PBQINTERNALINPUT.fields_by_name['cartoOutput'])
_PBQINTERNALINPUT.fields_by_name['cartoOutput'].containing_oneof = _PBQINTERNALINPUT.oneofs_by_name['hasCartoOutput']
DESCRIPTOR.message_types_by_name['PbQInternalOutput'] = _PBQINTERNALOUTPUT
DESCRIPTOR.message_types_by_name['PbQInternalInput'] = _PBQINTERNALINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbQInternalOutput = _reflection.GeneratedProtocolMessageType('PbQInternalOutput', (_message.Message,), dict(
  DESCRIPTOR = _PBQINTERNALOUTPUT,
  __module__ = 'PbQInternal_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbQInternalOutput)
  ))
_sym_db.RegisterMessage(PbQInternalOutput)

PbQInternalInput = _reflection.GeneratedProtocolMessageType('PbQInternalInput', (_message.Message,), dict(
  DESCRIPTOR = _PBQINTERNALINPUT,
  __module__ = 'PbQInternal_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbQInternalInput)
  ))
_sym_db.RegisterMessage(PbQInternalInput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
