# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbRpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbRpc.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0bPbRpc.proto\x12\x02pb\"6\n\x08PbRpcReq\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x03(\t\"V\n\x08PbRpcAck\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x12\x11\n\tretParams\x18\x04 \x03(\tB\n\n\x08hasErrorB\x02H\x03\x62\x06proto3')
)




_PBRPCREQ = _descriptor.Descriptor(
  name='PbRpcReq',
  full_name='pb.PbRpcReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.PbRpcReq.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='pb.PbRpcReq.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='pb.PbRpcReq.params', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=73,
)


_PBRPCACK = _descriptor.Descriptor(
  name='PbRpcAck',
  full_name='pb.PbRpcAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.PbRpcAck.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='pb.PbRpcAck.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='pb.PbRpcAck.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retParams', full_name='pb.PbRpcAck.retParams', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasError', full_name='pb.PbRpcAck.hasError',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=75,
  serialized_end=161,
)

_PBRPCACK.oneofs_by_name['hasError'].fields.append(
  _PBRPCACK.fields_by_name['error'])
_PBRPCACK.fields_by_name['error'].containing_oneof = _PBRPCACK.oneofs_by_name['hasError']
DESCRIPTOR.message_types_by_name['PbRpcReq'] = _PBRPCREQ
DESCRIPTOR.message_types_by_name['PbRpcAck'] = _PBRPCACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbRpcReq = _reflection.GeneratedProtocolMessageType('PbRpcReq', (_message.Message,), dict(
  DESCRIPTOR = _PBRPCREQ,
  __module__ = 'PbRpc_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbRpcReq)
  ))
_sym_db.RegisterMessage(PbRpcReq)

PbRpcAck = _reflection.GeneratedProtocolMessageType('PbRpcAck', (_message.Message,), dict(
  DESCRIPTOR = _PBRPCACK,
  __module__ = 'PbRpc_pb2'
  # @@protoc_insertion_point(class_scope:pb.PbRpcAck)
  ))
_sym_db.RegisterMessage(PbRpcAck)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
