# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbVisualTracker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PbConsts_pb2 as PbConsts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbVisualTracker.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x15PbVisualTracker.proto\x12\x02pb\x1a\x0ePbConsts.proto\"\xcc\x03\n\x07VTInput\x12$\n\x0bsoftCalFlag\x18\x01 \x01(\x0e\x32\r.pb.PbToggleTH\x00\x12\x31\n\x18returnCheckCameraQuality\x18\x02 \x01(\x0e\x32\r.pb.PbToggleTH\x01\x12#\n\nrelocation\x18\x03 \x01(\x0e\x32\r.pb.PbToggleTH\x02\x12.\n\x15returnCheckTempcoeffs\x18\x04 \x01(\x0e\x32\r.pb.PbToggleTH\x03\x12)\n\x10tempCaliTimeFlag\x18\x05 \x01(\x0e\x32\r.pb.PbToggleTH\x04\x12\'\n\x0erebootTimeFlag\x18\x06 \x01(\x0e\x32\r.pb.PbToggleTH\x05\x12\x1c\n\x12RTTLidarCheckAngle\x18\x07 \x01(\x02H\x06\x42\x10\n\x0ehasSoftCalFlagB\x1d\n\x1bhasReturnCheckCameraQualityB\x0f\n\rhasRelocationB\x1a\n\x18hasReturnCheckTempcoeffsB\x15\n\x13hasTempCaliTimeFlagB\x13\n\x11hasRebootTimeFlagB\x17\n\x15hasRTTLidarCheckAngle\"\x97\x02\n\x08VTOutput\x12\x1f\n\x06pickUp\x18\x04 \x01(\x0e\x32\r.pb.PbToggleTH\x00\x12#\n\tVTControl\x18\x05 \x01(\x0e\x32\x0e.pb.VTControlTH\x01\x12 \n\x07softCal\x18\x06 \x01(\x0e\x32\r.pb.PbToggleTH\x02\x12+\n\x12\x63heckCameraQuality\x18\x07 \x01(\x0e\x32\r.pb.PbToggleTH\x03\x12\"\n\tresetOdom\x18\x08 \x01(\x0e\x32\r.pb.PbToggleTH\x04\x42\x0b\n\thasPickUpB\x0e\n\x0chasVTControlB\x0c\n\nhasSoftCalB\x17\n\x15hasCheckCameraQualityB\x0e\n\x0chasResetOdom\"\"\n\x0eMapServerInput\x12\x10\n\x08reserved\x18\x01 \x01(\x05\"]\n\x0fMapServerOutput\x12#\n\tVTControl\x18\x01 \x01(\x0e\x32\x0e.pb.VTControlTH\x00\x12\x15\n\rcontrolParams\x18\x02 \x03(\x05\x42\x0e\n\x0chasVTControlB\x02H\x03\x62\x06proto3')
  ,
  dependencies=[PbConsts__pb2.DESCRIPTOR,])




_VTINPUT = _descriptor.Descriptor(
  name='VTInput',
  full_name='pb.VTInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='softCalFlag', full_name='pb.VTInput.softCalFlag', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnCheckCameraQuality', full_name='pb.VTInput.returnCheckCameraQuality', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relocation', full_name='pb.VTInput.relocation', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnCheckTempcoeffs', full_name='pb.VTInput.returnCheckTempcoeffs', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tempCaliTimeFlag', full_name='pb.VTInput.tempCaliTimeFlag', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rebootTimeFlag', full_name='pb.VTInput.rebootTimeFlag', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RTTLidarCheckAngle', full_name='pb.VTInput.RTTLidarCheckAngle', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasSoftCalFlag', full_name='pb.VTInput.hasSoftCalFlag',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasReturnCheckCameraQuality', full_name='pb.VTInput.hasReturnCheckCameraQuality',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasRelocation', full_name='pb.VTInput.hasRelocation',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasReturnCheckTempcoeffs', full_name='pb.VTInput.hasReturnCheckTempcoeffs',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasTempCaliTimeFlag', full_name='pb.VTInput.hasTempCaliTimeFlag',
      index=4, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasRebootTimeFlag', full_name='pb.VTInput.hasRebootTimeFlag',
      index=5, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasRTTLidarCheckAngle', full_name='pb.VTInput.hasRTTLidarCheckAngle',
      index=6, containing_type=None, fields=[]),
  ],
  serialized_start=46,
  serialized_end=506,
)


_VTOUTPUT = _descriptor.Descriptor(
  name='VTOutput',
  full_name='pb.VTOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickUp', full_name='pb.VTOutput.pickUp', index=0,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VTControl', full_name='pb.VTOutput.VTControl', index=1,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='softCal', full_name='pb.VTOutput.softCal', index=2,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkCameraQuality', full_name='pb.VTOutput.checkCameraQuality', index=3,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resetOdom', full_name='pb.VTOutput.resetOdom', index=4,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasPickUp', full_name='pb.VTOutput.hasPickUp',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasVTControl', full_name='pb.VTOutput.hasVTControl',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasSoftCal', full_name='pb.VTOutput.hasSoftCal',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasCheckCameraQuality', full_name='pb.VTOutput.hasCheckCameraQuality',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasResetOdom', full_name='pb.VTOutput.hasResetOdom',
      index=4, containing_type=None, fields=[]),
  ],
  serialized_start=509,
  serialized_end=788,
)


_MAPSERVERINPUT = _descriptor.Descriptor(
  name='MapServerInput',
  full_name='pb.MapServerInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved', full_name='pb.MapServerInput.reserved', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=790,
  serialized_end=824,
)


_MAPSERVEROUTPUT = _descriptor.Descriptor(
  name='MapServerOutput',
  full_name='pb.MapServerOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VTControl', full_name='pb.MapServerOutput.VTControl', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controlParams', full_name='pb.MapServerOutput.controlParams', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hasVTControl', full_name='pb.MapServerOutput.hasVTControl',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=826,
  serialized_end=919,
)

_VTINPUT.fields_by_name['softCalFlag'].enum_type = PbConsts__pb2._PBTOGGLET
_VTINPUT.fields_by_name['returnCheckCameraQuality'].enum_type = PbConsts__pb2._PBTOGGLET
_VTINPUT.fields_by_name['relocation'].enum_type = PbConsts__pb2._PBTOGGLET
_VTINPUT.fields_by_name['returnCheckTempcoeffs'].enum_type = PbConsts__pb2._PBTOGGLET
_VTINPUT.fields_by_name['tempCaliTimeFlag'].enum_type = PbConsts__pb2._PBTOGGLET
_VTINPUT.fields_by_name['rebootTimeFlag'].enum_type = PbConsts__pb2._PBTOGGLET
_VTINPUT.oneofs_by_name['hasSoftCalFlag'].fields.append(
  _VTINPUT.fields_by_name['softCalFlag'])
_VTINPUT.fields_by_name['softCalFlag'].containing_oneof = _VTINPUT.oneofs_by_name['hasSoftCalFlag']
_VTINPUT.oneofs_by_name['hasReturnCheckCameraQuality'].fields.append(
  _VTINPUT.fields_by_name['returnCheckCameraQuality'])
_VTINPUT.fields_by_name['returnCheckCameraQuality'].containing_oneof = _VTINPUT.oneofs_by_name['hasReturnCheckCameraQuality']
_VTINPUT.oneofs_by_name['hasRelocation'].fields.append(
  _VTINPUT.fields_by_name['relocation'])
_VTINPUT.fields_by_name['relocation'].containing_oneof = _VTINPUT.oneofs_by_name['hasRelocation']
_VTINPUT.oneofs_by_name['hasReturnCheckTempcoeffs'].fields.append(
  _VTINPUT.fields_by_name['returnCheckTempcoeffs'])
_VTINPUT.fields_by_name['returnCheckTempcoeffs'].containing_oneof = _VTINPUT.oneofs_by_name['hasReturnCheckTempcoeffs']
_VTINPUT.oneofs_by_name['hasTempCaliTimeFlag'].fields.append(
  _VTINPUT.fields_by_name['tempCaliTimeFlag'])
_VTINPUT.fields_by_name['tempCaliTimeFlag'].containing_oneof = _VTINPUT.oneofs_by_name['hasTempCaliTimeFlag']
_VTINPUT.oneofs_by_name['hasRebootTimeFlag'].fields.append(
  _VTINPUT.fields_by_name['rebootTimeFlag'])
_VTINPUT.fields_by_name['rebootTimeFlag'].containing_oneof = _VTINPUT.oneofs_by_name['hasRebootTimeFlag']
_VTINPUT.oneofs_by_name['hasRTTLidarCheckAngle'].fields.append(
  _VTINPUT.fields_by_name['RTTLidarCheckAngle'])
_VTINPUT.fields_by_name['RTTLidarCheckAngle'].containing_oneof = _VTINPUT.oneofs_by_name['hasRTTLidarCheckAngle']
_VTOUTPUT.fields_by_name['pickUp'].enum_type = PbConsts__pb2._PBTOGGLET
_VTOUTPUT.fields_by_name['VTControl'].enum_type = PbConsts__pb2._VTCONTROLT
_VTOUTPUT.fields_by_name['softCal'].enum_type = PbConsts__pb2._PBTOGGLET
_VTOUTPUT.fields_by_name['checkCameraQuality'].enum_type = PbConsts__pb2._PBTOGGLET
_VTOUTPUT.fields_by_name['resetOdom'].enum_type = PbConsts__pb2._PBTOGGLET
_VTOUTPUT.oneofs_by_name['hasPickUp'].fields.append(
  _VTOUTPUT.fields_by_name['pickUp'])
_VTOUTPUT.fields_by_name['pickUp'].containing_oneof = _VTOUTPUT.oneofs_by_name['hasPickUp']
_VTOUTPUT.oneofs_by_name['hasVTControl'].fields.append(
  _VTOUTPUT.fields_by_name['VTControl'])
_VTOUTPUT.fields_by_name['VTControl'].containing_oneof = _VTOUTPUT.oneofs_by_name['hasVTControl']
_VTOUTPUT.oneofs_by_name['hasSoftCal'].fields.append(
  _VTOUTPUT.fields_by_name['softCal'])
_VTOUTPUT.fields_by_name['softCal'].containing_oneof = _VTOUTPUT.oneofs_by_name['hasSoftCal']
_VTOUTPUT.oneofs_by_name['hasCheckCameraQuality'].fields.append(
  _VTOUTPUT.fields_by_name['checkCameraQuality'])
_VTOUTPUT.fields_by_name['checkCameraQuality'].containing_oneof = _VTOUTPUT.oneofs_by_name['hasCheckCameraQuality']
_VTOUTPUT.oneofs_by_name['hasResetOdom'].fields.append(
  _VTOUTPUT.fields_by_name['resetOdom'])
_VTOUTPUT.fields_by_name['resetOdom'].containing_oneof = _VTOUTPUT.oneofs_by_name['hasResetOdom']
_MAPSERVEROUTPUT.fields_by_name['VTControl'].enum_type = PbConsts__pb2._VTCONTROLT
_MAPSERVEROUTPUT.oneofs_by_name['hasVTControl'].fields.append(
  _MAPSERVEROUTPUT.fields_by_name['VTControl'])
_MAPSERVEROUTPUT.fields_by_name['VTControl'].containing_oneof = _MAPSERVEROUTPUT.oneofs_by_name['hasVTControl']
DESCRIPTOR.message_types_by_name['VTInput'] = _VTINPUT
DESCRIPTOR.message_types_by_name['VTOutput'] = _VTOUTPUT
DESCRIPTOR.message_types_by_name['MapServerInput'] = _MAPSERVERINPUT
DESCRIPTOR.message_types_by_name['MapServerOutput'] = _MAPSERVEROUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VTInput = _reflection.GeneratedProtocolMessageType('VTInput', (_message.Message,), dict(
  DESCRIPTOR = _VTINPUT,
  __module__ = 'PbVisualTracker_pb2'
  # @@protoc_insertion_point(class_scope:pb.VTInput)
  ))
_sym_db.RegisterMessage(VTInput)

VTOutput = _reflection.GeneratedProtocolMessageType('VTOutput', (_message.Message,), dict(
  DESCRIPTOR = _VTOUTPUT,
  __module__ = 'PbVisualTracker_pb2'
  # @@protoc_insertion_point(class_scope:pb.VTOutput)
  ))
_sym_db.RegisterMessage(VTOutput)

MapServerInput = _reflection.GeneratedProtocolMessageType('MapServerInput', (_message.Message,), dict(
  DESCRIPTOR = _MAPSERVERINPUT,
  __module__ = 'PbVisualTracker_pb2'
  # @@protoc_insertion_point(class_scope:pb.MapServerInput)
  ))
_sym_db.RegisterMessage(MapServerInput)

MapServerOutput = _reflection.GeneratedProtocolMessageType('MapServerOutput', (_message.Message,), dict(
  DESCRIPTOR = _MAPSERVEROUTPUT,
  __module__ = 'PbVisualTracker_pb2'
  # @@protoc_insertion_point(class_scope:pb.MapServerOutput)
  ))
_sym_db.RegisterMessage(MapServerOutput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
